version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: social_posts_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: social_posts_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - social_posts_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: social_posts_backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:password123@mongodb:27017/social_posts_db?authSource=admin
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongodb
    networks:
      - social_posts_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: social_posts_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8080/api
    depends_on:
      - backend
    networks:
      - social_posts_network

volumes:
  mongodb_data:
    driver: local

networks:
  social_posts_network:
    driver: bridge
